class GPIO_config():
    LEFT_FRONT_MOTOR = 5
    LEFT_REAR_MOTOR = 26
    RIGHT_FRONT_MOTOR = 13
    RIGHT_REAR_MOTOR = 6
    GPIO_DHT = 4
    GPIO_TRIGGER = 18
    GPIO_ECHO = 24
    HORIZONTAL_SERV0 = 4
    VERTICAL_SERVO = 3